"""Shared pytest fixtures for news_sentiment tests."""

from __future__ import annotations

from datetime import datetime

import numpy as np
import pandas as pd
import pytest
from news_sentiment.datasources.synthetic import SyntheticSource
from news_sentiment.scoring.lexicon import LexiconScorer
from news_sentiment.types import ScoredItem


@pytest.fixture
def trading_days() -> pd.DatetimeIndex:
    """A 600-day business-day index used by feature tests."""
    return pd.bdate_range("2020-01-01", periods=600, name="date")


@pytest.fixture
def synthetic_scored_items() -> list[ScoredItem]:
    """A reproducible list of scored items spanning the trading_days window.

    Generated by SyntheticSource → LexiconScorer so the pipeline-shape data
    flow is exercised end-to-end inside the fixture, not just feature-level
    arithmetic. Deterministic.
    """
    src = SyntheticSource(items_per_day_mean=2.0, seed=0)
    raw = src.fetch_raw("FAKE", datetime(2020, 1, 1), datetime(2022, 5, 1))
    return LexiconScorer().score(raw)


@pytest.fixture
def synthetic_prices() -> pd.DataFrame:
    """600-day business-day OHLCV (log-normal) — for end-to-end-ish tests."""
    rng = np.random.default_rng(0)
    n = 600
    dates = pd.bdate_range("2020-01-01", periods=n)
    closes = 100 * np.exp(np.cumsum(rng.normal(0.0003, 0.01, n)))
    return pd.DataFrame(
        {
            "open": closes,
            "high": closes * 1.005,
            "low": closes * 0.995,
            "close": closes,
            "volume": rng.integers(1_000_000, 5_000_000, n),
        },
        index=dates,
    )
